---
  - hosts:  localhost
    become: yes
    vars:
      olam_version: "1.0-1.el8"
    vars_files:
      - olam_repositories.yml
    tasks:
      - name: Enabling repositories {{ items }}
        ansible.builtin.dnf:
          enablerepo: "{{ item }}"
        loop: "{{ repositories }}"
      - name: Installing olam
        ansible.builtin.dnf:
          name: oraclelinux-automation-manager-release-el8-{{ olam_version }}
          state: present
